import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

day = pd.read_csv("C:/UB/MBKM/BANGKIT/Penalaksanaan/Belajar Analisis Data dengan Python/Proyek/day_clean.csv")
hour = pd.read_csv("C:/UB/MBKM/BANGKIT/Penalaksanaan/Belajar Analisis Data dengan Python/Proyek/hour_clean.csv")
day_numeric = day.select_dtypes(include=['number'])
hour_numeric = hour.select_dtypes(include=['number'])
st.title('Sharing Bike Case')

st.write(
    """Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return 
    back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return 
    back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of 
    over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, 
    environmental and health issues.
    Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by
    these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration
    of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into
    a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important
    events in the city could be detected via monitoring these data.
    """
)

st.header('Characteristic of Data Sharing Bike')
st.text("Here's the characteristic of data based on their corelation")


col1, col2 = st.columns(2)
with col1:
    st.subheader("Day correlation")
    corr = day_numeric.corr()
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(corr, annot=True, cmap='inferno', fmt=".2f", linewidths=0.5, ax=ax)
    ax.set_title('Day Dataset', fontsize=16, fontweight='bold')
    st.pyplot(fig)
    
with col2:
    st.subheader("Hour correlation")
    corr = hour_numeric.corr()
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(corr, annot=True, cmap='inferno', fmt=".2f", linewidths=0.5, ax=ax)
    ax.set_title('Hour Dataset', fontsize=16, fontweight='bold')
    st.pyplot(fig)

# Plot function
def plot_hourly_users(hour_df):
    sum_hr = hour_df.groupby(by="hr").agg({
        'casual': 'sum',
        'registered': 'sum'
    }).reset_index()

    hours = sum_hr['hr']
    casual = sum_hr['casual']
    registered = sum_hr['registered']

    # Lebar total bar
    total_width = 0.8
    # Lebar setiap bar
    bar_width = total_width / 2


    # Membuat bar plot
    plt.figure(figsize=(10, 6))
    plt.bar(hours, casual, width=bar_width, label='Casual')
    plt.bar(hours, registered, width=bar_width, label='Registered', bottom=casual)

    # Menambahkan label dan judul
    plt.xlabel('Hour', fontsize=16, fontweight='bold')
    plt.ylabel('Count', fontsize=16, fontweight='bold')
    # plt.title('Casual and Registered Users by Hour', fontsize=20, fontweight='bold')
    plt.xticks(hours)
    plt.legend()

    return plt

def plot_weather_users(df):
    sum_wet_day = df.groupby(by="weathersit").agg({
        'casual': ['sum'],
        'registered': ['sum']
    }).reset_index()
    wet_hour = sum_wet_day['weathersit']
    casual_sum = sum_wet_day['casual']['sum']
    registered_sum = sum_wet_day['registered']['sum']

    total_width = 0.8
    bar_width = total_width / 2

    weather_mapping = {1: 'Clear', 2: 'Mist', 3: 'Light Snow', 4: 'Heavy Rain'}

    weather_labels = [weather_mapping[hour] for hour in wet_hour]

    plt.figure(figsize=(10, 6))
    plt.bar(wet_hour, casual_sum, width=bar_width, label='Casual')
    plt.bar(wet_hour, registered_sum, width=bar_width, label='Registered', bottom=casual_sum)

    plt.xticks([i for i in wet_hour], weather_labels, ha='center')

    plt.xlabel('Weather', fontsize=16, fontweight='bold')
    plt.ylabel('Count', fontsize=16, fontweight='bold')
    # plt.title('Casual and Registered Users by Weather', fontsize=20, fontweight='bold')
    plt.legend()

    return plt

def plot_work_day_users(hour_df):
    sum_work_hour = hour_df.groupby(by="workingday").agg({
        'casual': 'sum',
        'registered': 'sum'
    }).reset_index()
    
    work_day = sum_work_hour['workingday']
    casual_sum = sum_work_hour['casual']
    registered_sum = sum_work_hour['registered']

    work_mapping = {1: 'Weekday', 0: 'Weekend'}
    work_label = [work_mapping[day] for day in work_day]

    # Menghitung total pengguna (casual + registered) untuk setiap kategori hari kerja
    total_users = [c + r for c, r in zip(casual_sum, registered_sum)]

    # Warna untuk setiap potongan pie
    colors = ['#ff9999', '#66b3ff']

    plt.figure(figsize=(10, 6))
    plt.pie(total_users, labels=work_label, autopct='%1.1f%%', startangle=140, colors=colors, explode=(0.1, 0))

    # Menambahkan lingkaran di tengah sebagai efek donat
    centre_circle = plt.Circle((0,0),0.70,fc='white')
    fig = plt.gcf()
    fig.gca().add_artist(centre_circle)

    # plt.title('Distribution of Users by Working Day', fontsize=20, fontweight='bold')
    plt.axis('equal')  # Memastikan lingkaran menjadi lingkaran dan bukan elips

    return plt

st.header('Evaluation of The Dataset')
st.text("Here's the analysis of data by visualization and explanation")


tab1, tab2, tab3 = st.tabs(["By Hour", "By Weather", "By Working Day"])

with tab1:
    st.header("Casual and Registered User By Hour in 2011-2012")
    with st.container():
        plot = plot_hourly_users(hour)
        st.pyplot(plot)
        with st.expander("See explanation"):
            st.write(
            """Based on the analysis and visualization conducted, it is found that the 'hr' feature shows a fairly positive correlation with the usage of bike sharing services, as observed in both casual and registered users. From the visualizations, it is evident that for casual users, the usage of bike sharing services tends to increase in the morning from 6 AM to 5 PM and then gradually decrease afterward. For registered users, there is a similar trend as casual users but with more fluctuations, albeit the usage is significantly higher compared to casual users.
            """
        )
    
with tab2:
    st.header("Casual and Registered User By Weather in 2011-2012")
    with st.container():
        col1, col2 = st.columns(2)
        with col1:
            st.subheader('By Hour')
            plot = plot_weather_users(hour)
            st.pyplot(plot)
        
        with col2:
            st.subheader('By Day')
            plot = plot_weather_users(day)
            st.pyplot(plot)
        with st.expander("See explanation"):
            st.write(
            """From the weather perspective, the variable "weathersit" shows a negative correlation (corr coefficient = -0.30) with the usage of bike sharing services. The characteristics of "weathersit" indicate that lower values correspond to clearer/more conducive weather conditions. Based on the visualization results, it is also observed that the usage of bike sharing services increases significantly during clear weather (weathersit = 1) and decreases drastically during rainy, snowy, and stormy conditions.
            """
        )
    
with tab3:
    with st.container():
        st.header("Casual and Registered User By Working Day in 2011-2012")
        plot = plot_work_day_users(hour)
        st.pyplot(plot)
        with st.expander("See explanation"):
            st.write(
            """When viewed from the perspective of the day condition (whether it's a working day or a holiday), there is a negative correlation with casual users (corr coefficient = -0.52) and a positive correlation with registered users (corr coefficient = 0.30). A working day is denoted as 1 and a holiday is denoted as 0, thus it is found that on working days, casual users decrease while registered users increase. Conversely, on holidays, casual users increase while registered users decrease. However, the influence of these two variables makes the correlation between working days and total users not very significant (corr coefficient 0.06). Based on the visualization, it is found that during working days, the demand for bike sharing services is higher with a percentage of 69.6%. This value surpasses the demand for bike sharing services on weekends, which only reaches 30.4%.
            """
        )


st.caption('Copyright (c) 2024')